CC = gcc -g

priority_queue_while.c:
	${CC} priority_queue_while.c.c -o app_priority_queue_while.c

priority_queue:
	${CC} priority_queue.c -o app_priority_queue

maximun_heap:
	${CC} maximun_heap.c -o app_maximun_heap

complete_binary_tree:
	${CC} complete_binary_tree.c -o app_complete_binary_tree

clean:
	rm -rf app*
