CC = gcc -g

graph:
	${CC} graph.c -o app_graph

topological_sort:
	${CC} topological_sort.c -o app_topological_sort

all_pairs_shortest_path:
	${CC} all_pairs_shortest_path.c -o app_all_pairs_shortest_path

clean:
	rm -rf app*
