CC = gcc -g

minimun_spanning_tree:
	${CC} minimun_spanning_tree.c -o app_minimun_spanning_tree

diameter_of_a_tree:
	${CC} diameter_of_a_tree.c -o app_diameter_of_a_tree

ariticulation_point:
	${CC} ariticulation_point.c -o app_ariticulation_point

graph:
	${CC} graph.c -o app_graph

topological_sort:
	${CC} topological_sort.c -o app_topological_sort

all_pairs_shortest_path:
	${CC} all_pairs_shortest_path.c -o app_all_pairs_shortest_path

clean:
	rm -rf app*
