CC = gcc -g

breadth_first_search:
	${CC} breadth_first_search.c -o app_breadth_first_search

depth_first_search:
	${CC} depth_first_search.c -o app_depth_first_search

graph:
	${CC} graph.c -o app_graph

clean:
	rm -rf app*
