CC = gcc -g

minimum_cost_sort:
	${CC} minimum_cost_sort.c -o app_minimum_cost_sort

the_num_of_inversions:
	${CC} the_num_of_inversions.c -o app_the_num_of_inversions

counting_sort:
	${CC} counting_sort.c -o app_counting_sort

quick_sort:
	${CC} quick_sort.c -o app_quick_sort

partition:
	${CC} partition.c -o app_partition

merge_sort:
	${CC} merge_sort.c -o app_merge_sort

clean:
	rm -rf app*
