CC = gcc -g

counting_sort:
	${CC} counting_sort.c -o app_counting_sort

quick_sort:
	${CC} quick_sort.c -o app_quick_sort

partition:
	${CC} partition.c -o app_partition

merge_sort:
	${CC} merge_sort.c -o app_merge_sort

clean:
	rm -rf app*
