CC = gcc -g

test_p:
	${CC} test_p.c -o app_test_p

test_height:
	${CC} test_height.c -o app_test_height

binary_search_tree_while.c:
	${CC} binary_search_tree_while.c.c -o app_binary_search_tree_while.c -lm

balance_binary_search_tree:
	${CC} balance_binary_search_tree.c -o app_balance_binary_search_tree

binary_search_tree:
	${CC} binary_search_tree.c -o app_binary_search_tree

clean:
	rm -rf app*
