CC = gcc -g

balance_binary_search_tree:
	${CC} balance_binary_search_tree.c -o app_balance_binary_search_tree

binary_search_tree:
	${CC} binary_search_tree.c -o app_binary_search_tree

clean:
	rm -rf app*
