CC = gcc -g

longest_increasing_subsequence:
	${CC} longest_increasing_subsequence.c -o app_longest_increasing_subsequence

knapsack_problem:
	${CC} knapsack_problem.c -o app_knapsack_problem

coin-changing-problem:
	${CC} coin-changing-problem.c -o app_coin-changing-problem

clean:
	rm -rf app*
