CC = gcc -g

power:
	${CC} power.c -o app_power

greatest_common_divisor:
	${CC} greatest_common_divisor.c -o app_greatest_common_divisor

is_prime:
	${CC} is_prime.c -o app_is_prime -lm

clean:
	rm -rf app*
