CC = gcc -g

reconstruction_of_the_tree:
	${CC} reconstruction_of_the_tree.c -o app_reconstruction_of_the_tree

tree_walk:
	${CC} tree_walk.c -o app_tree_walk

binary_tree:
	${CC} binary_tree.c -o app_binary_tree

rooted_tree:
	${CC} rooted_tree.c -o app_rooted_tree

clean:
	rm -rf app*
