CC = gcc -g

stack:
	${CC} stack.c -o app_stack

queue:
	${CC} queue.c -o app_queue

doubly_linked_list:
	${CC} doubly_linked_list.c -o app_doubly_linked_list

compute_area:
	${CC} compute_area.c -o app_compute_area

clean:
	rm -rf app*