CC = gcc -g

linear_search:
	${CC} linear_search.c -o app_linear_search


binary_search:
	${CC} binary_search.c -o app_binary_search

dictionary:
	${CC} dictionary.c -o app_dictionary

clean:
	rm -rf app*