CC = gcc -g

matrix_chain_multiplication:
	${CC} matrix_chain_multiplication.c -o app_matrix_chain_multiplication

longest_common_subsequence:
	${CC} longest_common_subsequence.c -o app_longest_common_subsequence

fibonacci_number:
	${CC} fibonacci_number.c -o app_fibonacci_number
	
clean:
	rm -rf app*
