CC = gcc -g

segment_intersections:
	${CC} segment_intersections.c -o app_segment_intersections

convex_hull:
	${CC} convex_hull.c -o app_convex_hull -lm

polygon_point_containment:
	${CC} polygon_point_containment.c -o app_polygon_point_containment -lm

cross_points_of_circles:
	${CC} cross_points_of_circles.c -o app_cross_points_of_circles -lm

cross_point_of_a_circle_and_a_line:
	${CC} cross_point_of_a_circle_and_a_line.c -o app_cross_point_of_a_circle_and_a_line -lm

cross_point:
	${CC} cross_point.c -o app_cross_point

counter_clockwise:
	${CC} counter_clockwise.c -o app_counter_clockwise -lm

intersection:
	${CC} intersection.c -o app_intersection -lm

distance:
	${CC} distance.c -o app_distance -lm

reflection:
	${CC} reflection.c -o app_reflection -lm

projection:
	${CC} projection.c -o app_projection -lm

parallel_orthogonal:
	${CC} parallel_orthogonal.c -o app_parallel_orthogonal

geometry:
	${CC} geometry.c -o app_geometry -lm

clean:
	rm -rf app*
