CC = gcc -g

reflection:
	${CC} reflection.c -o app_reflection -lm

projection:
	${CC} projection.c -o app_projection -lm

parallel_orthogonal:
	${CC} parallel_orthogonal.c -o app_parallel_orthogonal

geometry:
	${CC} geometry.c -o app_geometry -lm

clean:
	rm -rf app*
