CC = gcc -g

cross_point_of_a_circle_and_a_line:
	${CC} cross_point_of_a_circle_and_a_line.c -o app_cross_point_of_a_circle_and_a_line -lm

cross_point:
	${CC} cross_point.c -o app_cross_point

counter_clockwise:
	${CC} counter_clockwise.c -o app_counter_clockwise -lm

intersection:
	${CC} intersection.c -o app_intersection -lm

distance:
	${CC} distance.c -o app_distance -lm

reflection:
	${CC} reflection.c -o app_reflection -lm

projection:
	${CC} projection.c -o app_projection -lm

parallel_orthogonal:
	${CC} parallel_orthogonal.c -o app_parallel_orthogonal

geometry:
	${CC} geometry.c -o app_geometry -lm

clean:
	rm -rf app*
