CC = gcc -g

single_source_shortest_path_2:
	${CC} single_source_shortest_path_2.c -o app_single_source_shortest_path_2

single_source_shortest_path_1:
	${CC} single_source_shortest_path_1.c -o app_single_source_shortest_path_1

test_2D:
	${CC} test_2D.c -o app_test_2D

minimum_spanning_tree:
	${CC} minimum_spanning_tree.c -o app_minimum_spanning_tree

clean:
	rm -rf app*
