CC = gcc -g

koch_curve:
	${CC} koch_curve.c -o app_koch_curve -lm

exhaustive_search:
	${CC} exhaustive_search.c -o app_exhaustive_search

find_maximum:
	${CC} find_maximum.c -o app_find_maximum

clean:
	rm -rf app*
